apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-transaction-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bank-transaction-manager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-transaction-manager-service
            port:
              number: 8080